spring.application.name=api-gateway
##############################################
# Server Port
##############################################
server.port=9090


##############################################
# Eureka Client
##############################################
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true


###########################################################
# ROUTE 1 - hello-client   (Client - Gateway - hello-client)
###########################################################
spring.cloud.gateway.server.webflux.routes[0].id=hello-client-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://helloworld-client
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/hello/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/hello/(?<segment>.*), /${segment}


###########################################################
# ROUTE 2 - employee-client
###########################################################
spring.cloud.gateway.server.webflux.routes[1].id=employee-client-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://employee-client
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/emp/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/emp/(?<segment>.*), /${segment}

# ROUTE 3 - shopstop-service (acts as client calling customer-service)
###########################################################
# ROUTE 3 - shopstop-service  (acts as client of customer-service)
###########################################################

# A unique identifier for this route inside API Gateway
spring.cloud.gateway.server.webflux.routes[2].id=shopstop-client-route

# Service to forward the request to (using Eureka load balancing)
spring.cloud.gateway.server.webflux.routes[2].uri=lb://shopstop-service

# Predicate to match incoming request paths starting with /reg/
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/reg/**

# # Remove the /reg/ prefix before forwarding the request to shopstop-service
# Example:
# Incoming  - /reg/client/customers
# Forwarded - /client/customers
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/reg/(?<segment>.*), /${segment}


##############################################
# Actuator
##############################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Required to enable CORS handler for WebFlux Gateway
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

# CORS for all paths
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedOrigins[0]=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedMethods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedMethods[4]=OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowedHeaders[0]=*
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations."/**".allowCredentials=true

