spring.application.name=product-restapi

# Tomcat Server properties
server.port=8088
server.servlet.context-path=/producthive


# MySQL Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/producthive?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hiberanate - JPA Properties
# Tables will be created Automatically in the Database
# update - Creates table & updates data into table
# create - Creates new table & adds records for each server restart
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true